### ISSUE TITLE
Writable directory question

### ISSUE THREAD

**Issue by kirill-mally** [jim-parry/CodeIgniter4-website#2]
Hi,
I'm sorry if I asked not in correct branch or project.

My question is about work with /writable directory.
Totally like the approach of setting index.php into separate folder and dividing writable files as separate.
But when I tried to recreate the workflow for myself, I faced the problem, that whenever I put for example:
- /writable/minified - stylesheets and scripts that are dynamically minified and written during the load.
- /writable/uploads/avatar.gif - dummy image file for test.

How can I access them from frontend side, for example in header, while loading stylesheets:
`<link rel='stylesheet' type='text/css' href='[domain]/writable/minified/core.min.css'>`
And I understand that by logic you simply can't access secured and outer directory. Then how to get the content of the file by link? Through some specific helper and read of file?

Or for e.g. for load of image:
`<img class="preloader-logo" src="[domain]/writable/uploads/avatar.gif" />`
anywhere on the frontend etc.

Thank you for information and really hope you will not delete question or can answer me directly. I'm confused about this one.

**Comment by jim-parry** [comment]
You can't access the writeable folder like you are trying. You need to make a folder inside /public if you want the resources to be browser-accessible, for instance /public/minified and /public/uploads. These would then be referenced as <img src='/uploads/avatar.gif''>.

I think a similar question came up on the forum.
